name: Deploy API
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t resasalle-api:latest .

      - name: Compress Docker Image
        run: docker save -o api-image.tar resasalle-api:latest

      - name: Transfer Image to API Server
        run: scp -o StrictHostKeyChecking=no api-image.tar docker-compose.yml resasalle-api@10.10.10.43:/opt/resasalleapi/

      - name: Deploy on API Server
        run: |
          ssh -o StrictHostKeyChecking=no resasalle-api@10.10.10.43 << 'EOF'
            cd /opt/resasalleapi
            docker load -i api-image.tar
            docker compose up -d
            rm api-image.tar
            docker image prune -f
          EOF